# ansible-playbook yml/install.yaml -i hosts.ini
---
- hosts: all
  become: yes
  tasks:

  - name: Update /etc/hosts
    copy:
      dest: "/etc/hosts"
      content: |
        127.0.0.1 localhost
        10.10.0.101 horse-master
        10.10.0.102 horse-node-1
        10.10.0.103 horse-node-2
        10.10.0.104 horse-node-2

- hosts: master
  become: true
  tasks:

  - name: Criando novo directorio
    file:
      path: /home/vagrant/nginx/
      state: directory

  - name: create wiki
    template:
      dest: /home/vagrant/nginx/docker-compose.yml
      src: nginx.yml

#  - name: Upgrade all apt packages
#    apt: upgrade=dist force_apt_get=yes

#  - name: install dockers
#    apt:
#      pkg:
#      - docker.io
#      - docker-compose
#      - htop
#      update_cache: yes
#      state: present


- hosts: nodes
  become: true
  tasks:
  - name: hello motherfocker
    #debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    debug: var=ansible_enp0s3.ipv4.address
    debug: var=ansible_eth0.ipv4.address
    #debug: var=hostvars[inventory_hostname]['ansible_default_ipv6']['address']
...