---
- hosts: all
  become: yes
  tasks:
  - name: Instalando o Nginx >-< np prx
    package:
      name: ['nginx','nginx-core','nginx-full','nginx-extras']
      state: present
  - name: Garantindo inicialização do Nginx
    service:
      name: ['nginx','nginx-core','nginx-full','nginx-extras']
      state: started
      enabled: yes
...