# ablubluble.yml
---
- name: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  hosts: all
  become: yes
  tasks:
  - name: Instalando o Nginx >-<
    package:
      name: ['nginx']
      state: present
  - name: Garantindo inicialização do Nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: copy file to vm
    vmware_guest_file_operation:
      copy:
        src: "~/vagrant/vagrantfiles/perola/ym/t.txt"
        dest: "/home/vagrant/t.txt"
        owner: vagrant
        group: vagrant
        mode: 644
