- hosts: vm1
  become: true
  become_user: root
  tasks:

    - name: install updates using dnf
      dnf:
        name: "*"
        state: latest
    
    - name: Criando novo directorio
      file:
        path: /home/vagrant/ok-centos
        state: directory

- hosts: vm2
  become: true
  become_user: root
  tasks:

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Criando novo directorio
      file:
        path: /home/vagrant/ok-ubuntu
        state: directory