- hosts: node1
  become: yes
  tasks:
  - name: Instalando o docker
    package:
      name: ['docker.io', 'docker-compose']
      state: present
  - name: Garantindo inicialização do docker
    service:
      name: docker
      state: started
      enabled: yes

- hosts: node2
  tasks:
  - name: Instalando o bancos postgres e mariadb
    package:
      name: ['postgres', 'mariadb']
      state: present
  - name: Garantindo inicialização dos bancos
    service:
      name: ['postgres', 'mariadb']
      state: started
      enabled: yes

- hosts: node3
  tasks:
  - name: configurando nfs
    package:
      name: nfs-kernel-server
      state: present